import { prisma } from "@/lib/prisma";
import { NextRequest, NextResponse } from "next/server";

// GET /api/measurements — List measurements with filters
export async function GET(request: NextRequest) {
  const role = request.headers.get("x-user-role");
  const userId = request.headers.get("x-user-id");

  if (!role || !userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { searchParams } = new URL(request.url);
  const search = searchParams.get("search") || "";
  const status = searchParams.get("status") || "ALL";

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const where: any = {};

  // Customers only see their own measurements
  if (role === "CUSTOMER") {
    where.customerId = userId;
  }

  if (status !== "ALL") {
    where.status = status;
  }

  if (search) {
    where.OR = [
      { label: { contains: search, mode: "insensitive" } },
      { roomName: { contains: search, mode: "insensitive" } },
      { doorType: { contains: search, mode: "insensitive" } },
      { customer: { name: { contains: search, mode: "insensitive" } } },
    ];
  }

  const measurements = await prisma.measurementUpload.findMany({
    where,
    orderBy: { createdAt: "desc" },
    include: {
      customer: { select: { name: true, phone: true } },
    },
  });

  return NextResponse.json({ measurements });
}

// POST /api/measurements — App/Customer uploads a measurement
export async function POST(request: NextRequest) {
  const userId = request.headers.get("x-user-id");

  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body = await request.json();
    const { label, roomName, doorType, notes, photos } = body;

    if (!label || !photos || !Array.isArray(photos) || photos.length === 0) {
      return NextResponse.json(
        { error: "Label and at least one photo are required" },
        { status: 400 }
      );
    }

    const measurement = await prisma.measurementUpload.create({
      data: {
        customerId: userId,
        label,
        roomName: roomName || null,
        doorType: doorType || null,
        notes: notes || null,
        photos, // Base64 strings or URLs generated by client
        status: "UPLOADED",
      },
    });

    return NextResponse.json({ measurement }, { status: 201 });
  } catch (error) {
    console.error("Create measurement error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
