"use client";

import { Button, Card, CardBody } from "@heroui/react";
import { Printer, Download } from "lucide-react";

interface BillFooterProps {
    /** Terms & conditions text */
    terms?: string | null;
    /** Additional notes */
    notes?: string | null;
    /** Company name for the signatory section */
    companyName?: string;
    /** Show print/download buttons */
    showActions?: boolean;
    /** Called when Print button is pressed */
    onPrint?: () => void;
    /** Called when Download PDF button is pressed */
    onDownload?: () => void;
}

export function BillFooter({
    terms,
    notes,
    companyName,
    showActions = true,
    onPrint,
    onDownload,
}: BillFooterProps) {
    const hasContent = terms || notes;

    return (
        <div className="space-y-4 mb-6">
            {/* Notes & Terms */}
            {hasContent && (
                <div className="grid lg:grid-cols-2 gap-4">
                    {notes && (
                        <Card shadow="sm">
                            <CardBody className="p-5">
                                <h3 className="font-semibold text-sm mb-2 text-default-600">
                                    Notes
                                </h3>
                                <p className="text-sm text-default-500 whitespace-pre-line">
                                    {notes}
                                </p>
                            </CardBody>
                        </Card>
                    )}
                    {terms && (
                        <Card shadow="sm">
                            <CardBody className="p-5">
                                <h3 className="font-semibold text-sm mb-2 text-default-600">
                                    Terms & Conditions
                                </h3>
                                <p className="text-sm text-default-500 whitespace-pre-line">
                                    {terms}
                                </p>
                            </CardBody>
                        </Card>
                    )}
                </div>
            )}

            {/* Action buttons */}
            {showActions && (
                <div className="flex items-center justify-end gap-3 no-print">
                    <Button
                        variant="bordered"
                        startContent={<Printer className="h-4 w-4" />}
                        onPress={onPrint || (() => window.print())}
                    >
                        Print
                    </Button>
                    <Button
                        variant="bordered"
                        startContent={<Download className="h-4 w-4" />}
                        onPress={
                            onDownload ||
                            (() => {
                                /* PDF generation can be added later */
                                window.print();
                            })
                        }
                    >
                        Download PDF
                    </Button>
                </div>
            )}

            {/* Authorized signatory (visible in print) */}
            <div className="hidden print:block mt-8">
                <div className="flex justify-between items-end">
                    <div className="text-[8pt] text-gray-400">
                        <p>Generated by HisaabKitaab</p>
                        <p>This is a computer-generated document</p>
                    </div>
                    <div className="text-right">
                        <div className="border-b border-gray-400 w-44 mb-1 h-10" />
                        <p className="text-[8pt] font-bold text-gray-500 uppercase tracking-wider">
                            Authorized Signatory
                        </p>
                        {companyName && (
                            <p className="text-[7pt] text-gray-400 mt-0.5">{companyName}</p>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
